version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja

    steps:
      - run:
          name: Installing dependancies
          command: |
            apk add --update git
            apk add --update openssh
      - run:
          name: Git settings
          command: |
            git config --global user.email 'nekarugo628@gmail.com'
            git config --global user.name 'catupper'
      - checkout
      - run:
          name: Generating current version
          command: |
            latexmk editorial.tex
            cp .latexmkrc ~/.latexmkrc
      - run:
          name: Commit to repository
          command: |
            git checkout release-pdf
            mkdir work
            cp editorial.pdf work/editorial.pdf
            git add work/editorial.pdf
            git commit -m "[CircleCI] Generate PDF @$(date +'%Y/%m/%d %I:%M') [ci skip]"
            git push origin release-pdf
