version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja

    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Generating TeX version
          command: |
            mkdir /tmp/artifacts;
            latexmk editorial.tex;
            cp editorial.pdf /tmp/artifacts/.

      - store_artifacts:
          path: /tmp/artifacts
            
      
