version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja

    working_directory: ~
    steps:
      - checkout
      - run:
          name: Generating TeX version
          command: |
            mkdir ~/work;
            latexmk editorial.tex;
            cp editorial.pdf ~/work/.

      - store_artifacts:
          path: ~/work
            
      
